### ISSUE TITLE
LocalDateTime.now throws an exception in JS, not JVM

### ISSUE THREAD

**Issue by bwbecker** [soc/scala-java-time#51]
The following test

```
      val n = LocalDateTime.now
      assert(n.isInstanceOf[LocalDateTime])
```
works fine in the JVM but fails in both my browser (Chrome) and a test suite built with ScalaTestPlus (a Play application).

The stack trace is

```
[info] LocalDateTimeSpec:
[info] LocalDateTime should
[info] - get the current date/time with now() *** FAILED ***
[info]   scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'getID__T' of null
[info]   at org.threeten.bp.ZoneId$.systemDefault(/Users/bwbecker/oat/src/oat3/modules/xplatform/js/target/scala-2.11/xplatform-test-fastopt.js:41144:71)
[info]   at {anonymous}()(/Users/bwbecker/oat/src/oat3/modules/xplatform/js/target/scala-2.11/xplatform-test-fastopt.js:75750:187)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/Users/bwbecker/oat/src/oat3/modules/xplatform/js/target/scala-2.11/xplatform-test-fastopt.js:46259:23)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(/Users/bwbecker/oat/src/oat3/modules/xplatform/js/target/scala-2.11/xplatform-test-fastopt.js:3010:7)
```

I'm using 
`"io.github.soc" %%% "scala-java-time" % "2.0.0-M5"`, `addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.13")`, and scala 2.11.8.

**Comment by cquiroz** [comment]
This project has been forked to https://github.com/cquiroz/scala-java-time. Can you try with the version there and report if you have the same problem?

**Comment by bwbecker** [comment]
Cloned the project and ran the test suite.  Everything passes.  However, I note that the only calls to `now` in the test suite are to `now(fixedClock)`.  Adding the single line `val now = LocalDateTime.now` causes the test suite to fail.

**Comment by bwbecker** [comment]
Cloned  https://github.com/cquiroz/scala-java-time.  Ran the test suite; everything passed.  Added the following to TestExamples.scala:

```
    val n = LocalDateTime.now
    println(s"\n\n ${n}\n\n")
```

Got
```
[error] Test org.threeten.bp.TestExamples.testExamples failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'getID__T' of null, took 0.008999936 sec
[error]     at org.threeten.bp.ZoneId$.systemDefault(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:48615)
[error]     at org.threeten.bp.TestExamples.testExamples(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:22676)
[error]     at org.threeten.bp.TestExamples$scalajs$testng$bootstrapper$.invoke(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:36138)
[error]     at io.github.soc.testng.TestNGExecuteTest.executeTestMethods$1(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:9408)
[error]     at io.github.soc.testng.TestNGExecuteTest.io$github$soc$testng$TestNGExecuteTest$$executeTestMethod(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:9557)
[error]     at io.github.soc.testng.TestNGExecuteTest.executeTests(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:9655)
[error]     at io.github.soc.testng.TestNGTask.execute(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:31634)
[error]     at io.github.soc.testng.TestNGTask.execute(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:31585)
[error]     at org.scalajs.testinterface.internal.Slave$$anonfun$8.apply$mcV$sp(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:114532)
[error]     at org.scalajs.testinterface.internal.Slave$$anonfun$8.apply(/Users/bwbecker/temp/cquiroz/scala-java-time/js/target/scala-2.11/scala-java-time-test-fastopt.js:114540)
```

Similar results when I used this library with my own code rather than soc/scala-java-time.

**Comment by cquiroz** [comment]
Ah ok, timezone support is still pending, see 
https://github.com/cquiroz/scala-java-time/issues/9

**Comment by soc** [comment]
This project is discontinued.
